#!/bin/bash

# chkconfig: - 85 15
# description: a high performance web server and proxy server

# nginx的pid文件路径、conf文件路径、执行路径
nginx_command=/usr/local/Nginx/sbin/nginx
nginx_config=/usr/local/Nginx/conf/nginx.conf
nginx_pid=/usr/local/Nginx/logs/nginx.pid
# prog的值要和执行命令nginx一致
prog="nginx" 
RETVAL=0
# 启用functions
. /etc/rc.d/init.d/functions
# 开启网络 
. /etc/sysconfig/network

# 检测网络 
[ ${NETWORKING} = "no" ] && exit 0
[ -x $nginx_command ] ||  exit 0

# 创建启动、停止、重载
start() {
	if [ -e $nginx_pid ];then
		echo -n "nginx already running..."
		exit 1
	fi
	# daemon 启动nginx
	echo -n "Startingprog: "
	daemon ${nginx_command} -c ${nginx_config}
	RETVAL=$?
	echo
	[ $RETVAL -eq 0 ] && touch /var/lock/subsys/nginx
	return $RETVAL
}

stop() {
	echo -n "Stoppingprog: "
	killproc ${nginx_command}
	RETVAL=$?
	echo
	[ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/nginx /usr/local/Nginx/logs/nginx.pid
}  

reload() {
	echo -n "Reloadingprog: "
	# kill -HUP `cat ${nginx_pid}`
	killproc ${nginx_command} -HUP
	RETVAL=$?
	echo
}

# See how we were called
case "$1" in
start)
	start
	;;
stop)
	stop
	;;
reload)
	reload
	;;
restart)
	stop
	start
	;;
status)
	status $prog
	RETVAL=$?
	;;
*)
	echo "Usage:prog {start|stop|restart|reload|status|help}"
	exit 1
esac
exit $RETVAL

